meta_product_name: "FIT"
meta_title: "FIT - Design unique, prefectly fitted clothes!"
meta_description: "FIT is a bespoke experience that enables clients to become their own designer by producing unique, made to measure garments.
Fighting Fast-Fashion one dress at a type, with style of course. "
meta_image: "logo_FIT.png" # should exist in `app/assets/images/
